baseURL = "https://arturmyszkowski.pl"
languageCode = "en-us"
title = "Artur Myszkowski | Senior Software Developer"
theme = "PaperMod"
ignoreLogs = ["warning-goldmark-raw-html"]
[markup.goldmark.renderer]
  unsafe= true
[params]
  [params.author]
    name = "Artur Myszkowski"
    
  [params.email]
    user = "contact"
    domain = "arturmyszkowski.pl"

  [params.label]
    display = true
    text = "Artur Myszkowski"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/rthrs"

  [[params.socialIcons]]
    name = "instagram"
    url = "https://www.instagram.com/artur6strings/"

  [[params.socialIcons]]
    name = "email"
    url = ""

  [[params.socialIcons]]
    name = "cv"
    title = "Resume"
    url = "/files/Artur_Myszkowski_Resume_2025_v4.pdf"
