# This is the main build configuration
[build]
  # This is the command Netlify will run to build your site
  command = """\
  git config core.quotepath false && \
  hugo --gc --minify --baseURL "${URL}"
  """
  # This is the directory that contains the final website files
  publish = "public"

# This section tells Netlify's build environment what to do
[context.production.environment]
  # This tells Netlify which version of Hugo to download and use.
  HUGO_VERSION = "0.148.2"
